- name: Install Flask API Daemon
  vars:
    domainname: ddns.net
    dir_path: "/opt"
    pwd: "/root/ansible-for-flask-api-server"
  hosts: localhost
  tasks:
    - name: Install Python3 and Flask
      yum: name={{ item }} state=installed
      with_items:
        - python34
        - python34-pip
        - openssl

    - pip:
        name: flask
        state: present

    - pip:
        name: pyopenssl
        state: present

    - name: Copy api.py
      copy:
        owner: root
        group: root
        mode: 0755
        src: "{{ pwd }}/files/api.py"
        dest: "{{ dir_path }}/api.py"

    - name: Copy self-signed certificate key
      copy:
        owner: root
        group: root
        mode: 0640
        src: "{{ pwd }}/files/server.key"
        dest: "{{ dir_path }}/server.key"

    - name: Copy self-signed certificate
      copy:
        owner: root
        group: root
        mode: 0640
        src: "{{ pwd }}/files/server.crt"
        dest: "{{ dir_path }}/server.crt"

    - name: Copy Systemd Service Config File
      copy:
        owner: root
        group: root
        mode: 0644
        src: "{{ pwd }}/files/flask-api.service"
        dest: /lib/systemd/system/flask-api.service

    - name: Copy rsyslog Config File
      copy:
        owner: root
        group: root
        mode: 0644
        src: "{{ pwd }}/files/flask-api.conf"
        dest: /etc/rsyslog.d/flask-api.conf

    - name: Run flask-api
      service:
        name: flask-api
        state: started

    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
