- name: Install Klein API Daemon
  vars:
    domainname: ddns.net
    dir_path: "/opt"
    pwd: "/root/ansible-for-klein-api-server"
  hosts: localhost
  tasks:
    - name: Install Python3 and Klein
      yum: name={{ item }} state=installed
      with_items:
        - python34
        - python34-pip
        - python34-devel
        - gcc
        - openssl

    - pip:
        name: twisted
        state: present
        executable: pip3

    - pip:
        name: klein
        state: present
        executable: pip3

    - name: Copy api.py
      copy:
        owner: root
        group: root
        mode: 0755
        src: "{{ pwd }}/files/api.py"
        dest: "{{ dir_path }}/api.py"

    - name: Copy self-signed certificate key
      copy:
        owner: root
        group: root
        mode: 0640
        src: "{{ pwd }}/files/server.key"
        dest: "{{ dir_path }}/server.key"

    - name: Copy self-signed certificate
      copy:
        owner: root
        group: root
        mode: 0640
        src: "{{ pwd }}/files/server.crt"
        dest: "{{ dir_path }}/server.crt"

    - name: Copy Systemd Service Config File
      copy:
        owner: root
        group: root
        mode: 0644
        src: "{{ pwd }}/files/klein-api.service"
        dest: /lib/systemd/system/klein-api.service

    - name: Copy rsyslog Config File
      copy:
        owner: root
        group: root
        mode: 0644
        src: "{{ pwd }}/files/klein-api.conf"
        dest: /etc/rsyslog.d/klein-api.conf

    - name: Run klein-api
      service:
        name: klein-api
        state: started

    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
